using AMS.Classes;
using DevExpress.DataAccess.Sql;
using DevExpress.XtraReports.UI;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace AMS
{
    public partial class frmCommitteeReport : DevExpress.XtraBars.Ribbon.RibbonForm
    {
        DataTable dtCommittee = new DataTable();
        XtraReportCommittee committeeReport = new XtraReportCommittee();

        public frmCommitteeReport()
        {
            InitializeComponent();
        }

        private void barButtonCancel_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            this.Close();
        }

        private void BindAttendanceToReport()
        {
            using (var adapt = new SqlDataAdapter("GET_BRETHREN_BY_COMMITTEE", Utilities.con))
            {
                adapt.SelectCommand.CommandType = CommandType.StoredProcedure;
                adapt.SelectCommand.Parameters.AddWithValue("@Committee_name", lueCommitteeReport.EditValue);
                adapt.Fill(dtCommittee);
                committeeReport.DataSource = dtCommittee;
            }
        }

        private void SetHeaders()
        {
            committeeReport.xrLabelCommittee.Text = lueCommitteeReport.Text;
            committeeReport.xrLabelUser.Text = "Generated by: " + frmLogin.Username; 
        }

        private void barButtonGenerate_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if (string.IsNullOrWhiteSpace(lueCommitteeReport.Text))
            {
                Utilities.ErrorMessage("Please Select Committee");
            }
            else
            {
            BindAttendanceToReport();
                if (dtCommittee.Rows.Count == 0)
                {
                    Utilities.ErrorMessage("No Record(s) found");
                }
                else
                {
                    SetHeaders();

                    committeeReport.xrTableCellChurchID.DataBindings.Add("Text", dtCommittee, dtCommittee.Columns["Church_Id"].ToString());
                    committeeReport.xrTableCellName.DataBindings.Add("Text", dtCommittee, dtCommittee.Columns["BrethrenName"].ToString());
                    committeeReport.xrTableCellStatus.DataBindings.Add("Text", dtCommittee, dtCommittee.Columns["Status"].ToString());
                    committeeReport.CreateDocument();

                    ReportPrintTool printTool = new ReportPrintTool(committeeReport);
                    printTool.ShowPreview();
                    this.Close();
                }
            }
        }

        private void frmcommitteeReport_Load(object sender, EventArgs e)
        {
            dtCommittee.Clear();
            Utilities.FillLookUpEdit(lueCommitteeReport, "GET_COMMITTEE", "committee_name", "committee_name");
        }
    }
}
