using AMS.Classes;
using DevExpress.XtraReports.UI;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace AMS
{
    public partial class frmGatheringSelection : DevExpress.XtraBars.Ribbon.RibbonForm
    {
        DataTable dtGathering = new DataTable();
        DataTable dtAttendance = new DataTable();
        XtraReportAttendance attendanceReport = new XtraReportAttendance();

        public frmGatheringSelection()
        {
            InitializeComponent();
        }

        private void GetGatheringList()
        {
            using (var adapt = new SqlDataAdapter("GET_GATHERINGS", Utilities.con))
            {
                dtGathering.Clear();
                adapt.SelectCommand.CommandType = CommandType.StoredProcedure;
                adapt.Fill(dtGathering);
                gridGathering.DataSource = dtGathering;
            }
        }

        private void frmGatheringSelection_Load(object sender, EventArgs e)
        {
            GetGatheringList();
        }

        private void BindAttendanceToReport()
        {
            using (var adapt = new SqlDataAdapter("ATTENDANCE_REPORT_NEW", Utilities.con))
            {
                adapt.SelectCommand.CommandType = CommandType.StoredProcedure;
                adapt.SelectCommand.Parameters.AddWithValue("@Gathering_Type", gridView1.GetFocusedRowCellValue("gathering_code").ToString());
                adapt.SelectCommand.Parameters.AddWithValue("@Date", Convert.ToDateTime(gridView1.GetFocusedRowCellValue("DateOfGathering").ToString()).ToShortDateString());
                adapt.Fill(dtAttendance);
                attendanceReport.DataSource = dtAttendance;
            }
        }

        private void SetHeaders()
        {
            attendanceReport.xrLabelGathering.Text = gridView1.GetFocusedRowCellValue("Gathering_Type").ToString();
            attendanceReport.xrLabelDate.Text = gridView1.GetFocusedRowCellValue("DateOfGathering").ToString();
            attendanceReport.xrLabelUser.Text = "Generated by: " + frmLogin.Username;
        }

        private void barButtonItem1_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            this.Hide();
        }

        private void barButtonItemAccept_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            BindAttendanceToReport();

            if (dtAttendance.Rows.Count == 0)
                Utilities.ErrorMessage("Gathering does not exists...");
            else
            {
                SetHeaders();

                GroupField gfBatch = new GroupField(dtAttendance.Columns["batch_time"].ToString());
                GroupField gfInterlocale = new GroupField(dtAttendance.Columns["Interlocale_Status"].ToString());
                attendanceReport.GroupHeader.GroupFields.Add(gfInterlocale);
                attendanceReport.GroupHeader.GroupFields.Add(gfBatch);

                attendanceReport.xrLabelInterlocale.DataBindings.Add("Text", dtAttendance, dtAttendance.Columns["Interlocale_Status"].ToString());
                attendanceReport.xrLabelBatch.DataBindings.Add("Text", dtAttendance, dtAttendance.Columns["batch_time_lbl"].ToString());
                attendanceReport.xrTableCellChurchID.DataBindings.Add("Text", dtAttendance, dtAttendance.Columns["Church_Id"].ToString());
                attendanceReport.xrTableCellName.DataBindings.Add("Text", dtAttendance, dtAttendance.Columns["BrethrenName"].ToString());
                attendanceReport.xrTableCellTimeIn.DataBindings.Add("Text", dtAttendance, dtAttendance.Columns["time_in"].ToString());
                attendanceReport.xrTableCellStatus.DataBindings.Add("Text", dtAttendance, dtAttendance.Columns["AttendanceStatus"].ToString());
                attendanceReport.xrTableCellLocale.DataBindings.Add("Text", dtAttendance, dtAttendance.Columns["locale"].ToString());
                attendanceReport.Name = gridView1.GetFocusedRowCellValue("Gathering_Type").ToString().Replace(" ", string.Empty);
                attendanceReport.CreateDocument();
                ReportPrintTool printTool = new ReportPrintTool(attendanceReport);
                printTool.ShowPreviewDialog();
            }
        }
    }
}
